trigger:
  branches:
    include:
      - main
      - feature

pr:
  branches:
    include:
      - main

pool:
  name: Azurecicd

variables:
  - group: dev

stages:

# =========================
# STAGE 1: VALIDATE
# =========================
- stage: Validate
  displayName: "Terraform Validate"

  jobs:
  - job: ValidateJob
    displayName: "Terraform Init and Validate"

    steps:

    - checkout: self
      displayName: "Checkout Code"

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'shailesh'
        backendAzureRmResourceGroupName: 'sit'
        backendAzureRmStorageAccountName: 'sitterraformstate2026'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'sit.terraform.tfstate'

    - task: TerraformTask@5
      displayName: "Terraform Validate"
      inputs:
        provider: 'azurerm'
        command: 'validate'


# =========================
# STAGE 2: PLAN
# =========================
- stage: Plan
  displayName: "Terraform Plan"

  dependsOn: Validate

  condition: succeeded()

  jobs:
  - job: PlanJob
    displayName: "Terraform Plan"

    steps:

    - checkout: self
      displayName: "Checkout Code"

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'shailesh'
        backendAzureRmResourceGroupName: 'sit'
        backendAzureRmStorageAccountName: 'sitterraformstate2026'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'sit.terraform.tfstate'

    - task: TerraformTask@5
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'shailesh'
        commandOptions: '-out=tfplan'


# =========================
# STAGE 3: APPLY
# =========================
- stage: Apply
  displayName: "Terraform Apply"

  dependsOn: Plan

  condition: succeeded()

  jobs:
  - job: ApplyJob
    displayName: "Terraform Apply"

    steps:

    - checkout: self
      displayName: "Checkout Code"

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'shailesh'
        backendAzureRmResourceGroupName: 'sit'
        backendAzureRmStorageAccountName: 'sitterraformstate2026'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'sit.terraform.tfstate'

    - task: TerraformTask@5
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'shailesh'
        commandOptions: '-auto-approve'